version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: airflowdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - airflow-network

  airflow-init:
    image: apache/airflow:2.5.0
    command: db init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@postgres:5432/airflowdb
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://root:root@postgres:5432/airflowdb
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=8858f8adde7eed8541ebbb82aee3a1c49cd017ef2e46c368
    depends_on:
      - postgres
      - redis
    networks:
      - airflow-network
    volumes:
      - ./airflow-data/dags:/opt/airflow/dags
      - ./airflow-data/plugins:/opt/airflow/plugins

  airflow-webserver:
    image: apache/airflow:2.5.0
    command: webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@postgres:5432/airflowdb
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://root:root@postgres:5432/airflowdb
      - AIRFLOW__WEBSERVER__SECRET_KEY=8858f8adde7eed8541ebbb82aee3a1c49cd017ef2e46c368
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - airflow-network
    volumes:
      - ./airflow-data/dags:/opt/airflow/dags
      - ./airflow-data/plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: apache/airflow:2.5.0
    command: scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@postgres:5432/airflowdb
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://root:root@postgres:5432/airflowdb
      - AIRFLOW__WEBSERVER__SECRET_KEY=8858f8adde7eed8541ebbb82aee3a1c49cd017ef2e46c368
    depends_on:
      - postgres
      - redis
    networks:
      - airflow-network
    volumes:
      - ./airflow-data/dags:/opt/airflow/dags
      - ./airflow-data/plugins:/opt/airflow/plugins

  airflow-worker:
    image: apache/airflow:2.5.0
    command: celery worker
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@postgres:5432/airflowdb
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://root:root@postgres:5432/airflowdb
      - AIRFLOW__WEBSERVER__SECRET_KEY=8858f8adde7eed8541ebbb82aee3a1c49cd017ef2e46c368
    depends_on:
      - postgres
      - redis
    networks:
      - airflow-network
    volumes:
      - ./airflow-data/dags:/opt/airflow/dags
      - ./airflow-data/plugins:/opt/airflow/plugins

volumes:
  postgres-data:

networks:
  airflow-network:
    driver: bridge